version: 0.2

env:
  variables:
    DOCKER_BUILD_IMAGE: 259525371233.dkr.ecr.us-east-2.amazonaws.com/test
    APPNAME: ecs-trivial-tomcat

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      ### ENVIRONMENT PREP ###
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - REV=$(git rev-parse --short HEAD)
  build:
    commands:
      ### BUILD YOUR WAR FILE ###
      - echo "FIXME - your code here"
  post_build:
    commands:
      ### BUILD THE DOCKER IMAGE ###
      - docker build -t "${APPNAME}" .
      - docker tag "${APPNAME}":latest "${DOCKER_BUILD_IMAGE}":"${REV}"
      - docker tag "${APPNAME}":latest "${DOCKER_BUILD_IMAGE}":latest
      - docker push "${DOCKER_BUILD_IMAGE}":"${REV}"
      - docker push "${DOCKER_BUILD_IMAGE}":latest
      ### DEPLOY THE ECS SERVICE ###
      - echo "FIXME - implement"